name: Quality Gates 

on: push
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Running Horus Security
        run: |
        curl -fsSL https://horusec.io/bin/install.sh | bash
        horusec start -p ./ -G "true"  -n "${GITHUB_REPOSITORY}_${GITHUB_REF##*/}"
